#!/usr/bin/env python
import sys
import logging
from mailpile.app import Main

formatter = '[%(asctime)s] {%(module)s:%(lineno)d} %(levelname)s - %(message)s'
logging.basicConfig(filename="/Users/halldor/.mailpile/mailpile.log", level=logging.DEBUG, format=formatter)

Main(sys.argv[1:])
